name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
    original_code:
      +enabled: true
      +materialized: table
      staging:
        + materialized: view
    example1:
      +enabled: true
      +materialized: incremental
    example2:
      +enabled: true
      materialized: view
    example3:
      +enabled: true
      ephemeral:
        +materialized: ephemeral
      incremental:
        +materialized: incremental
      views:
        +materialized: view
      tables:
        +materialized: table

seeds:
  jaffle_shop:
    example:
      +enabled: false


vars:
    dbt_metrics_calendar_model: metrics_calendar
    'dbt_date:time_zone': 'America/Chicago'
    load_date: